AllCops:
  TargetRubyVersion: 3.3.2
  NewCops: enable
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false